language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

before_script:
  - composer self-update
  - composer install --no-interaction
  
script:
  - ./vendor/bin/phpunit --colors=always

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
